<?php

########################################################################
# Extension Manager/Repository config file for ext: "reposearch"
#
# Auto generated by Extension Builder 2011-10-08
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Repository Search',
	'description' => 'search through multiple Extbase Repositories',
	'category' => 'plugin',
	'author' => 'Thomas Allmer',
	'author_email' => 'at@delusionworld.com',
	'author_company' => 'WEBTEAM GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'fluidce' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>